clear;
clc;
close all;
X = load('q1x.dat');
y = load('q1y.dat');
X = [ones(size((X),1),1) X];
[m n] = size(X);
pos = find(y==1);
neg = find(y==0);
hold on;
plot(X(pos,2),X(pos,3),'ro');
plot(X(neg,2),X(neg,3),'kx');
xlabel('X1');
ylabel('X2');
legend('Admitted','Not Admitted');
init_theta = zeros(n,1);
options = optimset('GradObj', 'on', 'MaxIter', 400);
[theta, cost] = fminunc(@(t)(LjcGradFun(t,X,y)), init_theta, options);
%[theta, cost] = fminunc(@(t)(R_NewtonFunc(t, X, y)), init_theta, options);
plot_X = [min(X(:,2))-2, max(X(:,2))+2];
plot_Y = -(theta(2).*plot_X + theta(1))/theta(3);
plot(plot_X, plot_Y);
hold off;